'use strict';
const router = require('express').Router();
const authRouter = require('./auth');
const managerRouter = require('./manager');
const studentRouter = require('./student');
const parentRouter = require('./parent');
const teacherRouter = require('./teacher');
const classRouter = require('./class');
const courseRouter = require('./course');
const timetableRouter =require('./timetable');
const appRouter = require('./app');
const schoolRouter = require('./school');
const newsRouter = require('./news');
const magazineRouter = require('./magazine');
const reportRouter = require('./report');
const calendarRouter = require('./calendar');
const galleryRouter = require('./gallery');
const assignment = require('./assignment');
const appointment = require('./appointment');
const chat = require('./chat');
const term = require('./term')

router.use('/app', appRouter);
router.use('/', authRouter);
router.use('/', managerRouter);
router.use('/', studentRouter);
router.use('/', parentRouter);
router.use('/', teacherRouter);
router.use('/', classRouter);
router.use('/', courseRouter);
router.use('/', timetableRouter);
router.use('/', schoolRouter);
router.use('/', newsRouter);
router.use('/', calendarRouter);
router.use('/', magazineRouter);
router.use('/', reportRouter);
router.use('/gallery', galleryRouter);
router.use('/',assignment);
router.use('/',appointment);
router.use('/', chat);
router.use('/',term);
module.exports = router;